#!/bin/bash
# ============================================================
# GitHub Secrets Configuration Script
# Este script configura os secrets necessários no GitHub
# ============================================================

echo "🔐 GitHub Secrets Configuration"
echo "================================"
echo ""
echo "Para configurar automaticamente, você precisa:"
echo "1. Gerar um token GitHub com permissão 'repo' e 'secrets'"
echo "2. Executar este script com: bash scripts/setup-github-secrets.sh"
echo ""
echo "OU configure manualmente em:"
echo "https://github.com/Cannalonga/PROJETO-PAGINAS-PARA-COMERCIO/settings/secrets/actions"
echo ""
echo "Secrets a configurar:"
echo "====================="
echo ""
echo "1. DATABASE_URL"
echo "   Tipo: Supabase PostgreSQL connection string"
echo "   Formato: postgresql://[user]:[password]@[host]:[port]/[database]?schema=public"
echo "   ⚠️  Use apenas a connection string de PRODUÇÃO"
echo ""
echo "2. NEXTAUTH_SECRET"
echo "   Tipo: Random secret string (32+ caracteres)"
echo "   Gerar com: openssl rand -base64 32"
echo "   ⚠️  Mantenha seguro! Não share com ninguém"
echo ""
echo "3. NEXT_PUBLIC_APP_URL"
echo "   Tipo: Production domain URL"
echo "   Formato: https://yourapp.com"
echo "   ⚠️  Sem slash no final"
echo ""
echo "4. NEXTAUTH_URL"
echo "   Tipo: Production domain URL (usually same as NEXT_PUBLIC_APP_URL)"
echo "   Formato: https://yourapp.com"
echo "   ⚠️  Sem slash no final"
echo ""
echo "============================================================"
echo "INSTRUÇÕES MANUAIS:"
echo "============================================================"
echo ""
echo "1. Vá para: https://github.com/Cannalonga/PROJETO-PAGINAS-PARA-COMERCIO/settings/secrets/actions"
echo ""
echo "2. Clique em 'New repository secret'"
echo ""
echo "3. Preencha cada secret conforme acima"
echo ""
echo "4. Verifique se todos os 4 secrets aparecem na lista"
echo ""
echo "5. Pronto! GitHub Actions rodará automaticamente"
echo ""
echo "✅ Após configurar os secrets, o workflow de segurança"
echo "   será acionado automaticamente no próximo push."
